// Responsive image props for the heavy content images. The manifest is
// generated by scripts/optimize-images.mjs; images not listed fall through
// unchanged (src only).
import manifest from "./content/image-manifest.json";

export function imgProps(src) {
  const m = manifest[src];
  if (!m) return { src };
  const props = { src: m.src, width: m.width, height: m.height };
  if (m.srcSet) {
    props.srcSet = m.srcSet;
    props.sizes = m.sizes;
  }
  return props;
}
